# Generated by Django 4.2.1 on 2023-05-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cisloPokoje', models.CharField(help_text='Zadejte číslo pokoje', max_length=50, verbose_name='Číslo pokoje')),
            ],
            options={
                'verbose_name': 'Pokoj',
                'verbose_name_plural': 'Pokoje',
                'ordering': ['cisloPokoje'],
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrezervace', models.PositiveIntegerField(help_text='Zadejte ID rezervace', max_length=50, unique=True, verbose_name='ID rezervace')),
                ('jmenoZakaznika', models.CharField(help_text='Zadejte jméno zákazníka', max_length=50, verbose_name='Jméno zákazníka')),
                ('prijmeniZakaznika', models.CharField(help_text='Zadejte příjmení zákazníka', max_length=50, verbose_name='Příjmení zákazníka')),
                ('datumRezervace', models.DateField(help_text='Zadejte datum začátku rezervace', verbose_name='Datum rezervace')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['idrezervace'],
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prijmeniZakaznika', models.CharField(help_text='Zadejte příjmení zákazníka', max_length=50, verbose_name='Příjmení zákazníka')),
                ('email', models.CharField(help_text='Zadejte email zákazníka', max_length=150, verbose_name='Email zákazníka')),
                ('telefon', models.IntegerField(help_text='Zadejte telefonní číslo zákazníka', max_length=9, verbose_name='Telefonní číslo zákazníka')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
                'ordering': ['prijmeniZakaznika'],
            },
        ),
    ]
