# Generated by Django 4.2.1 on 2023-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='profilovyObrazek',
            field=models.ImageField(default='uploads/defaultpfp.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='idrezervace',
            field=models.PositiveIntegerField(help_text='Zadejte ID rezervace', unique=True, verbose_name='ID rezervace'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='telefon',
            field=models.IntegerField(help_text='Zadejte telefonní číslo zákazníka', verbose_name='Telefonní číslo zákazníka'),
        ),
    ]
