# Generated by Django 4.2.1 on 2023-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0003_remove_rezervace_jmenozakaznika_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='pocetPosteli',
            field=models.PositiveIntegerField(default='1', help_text='Zadejte počet postelí', verbose_name='Počet postelí'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='cisloPokoje',
            field=models.CharField(help_text='Zadejte číslo pokoje', max_length=50, unique=True, verbose_name='Číslo pokoje'),
        ),
    ]
