# Generated by Django 4.2.1 on 2023-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0004_pokoj_pocetposteli_alter_pokoj_cislopokoje'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='jmenoZakaznika',
            field=models.CharField(default='honza', help_text='Zadejte jméno zákazníka', max_length=50, verbose_name='Jméno zákazníka'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='prijmeniZakaznika',
            field=models.CharField(default='honzík', help_text='Zadejte příjmení zákazníka', max_length=50, verbose_name='Příjmení zákazníka'),
        ),
    ]
